### ISSUE TITLE
Assertion failure from doBitplaneDmaRead

### ISSUE THREAD

**Issue by mras0** [dirkwhoffmann/vAmiga#615]
Since commit a90464c104a97e5dcefff9bffa44eb968628da85 ("Work on pokeBPLxPTL")

Anarchy - 3D Demo 2 ([pouet](https://www.pouet.net/prod.php?which=3091)) ([direct download](https://files.scene.org/get/mirrors/amigascne/Groups/A/Anarchy/ANARCHY-3dDemo2.dms)) crashes with an assertion failure in the rotating starwars scroller after "The Portal".

Backtrace:
```
vAmiga: /mnt/c/Prog/amiga/Misc/vAmiga/Emulator/Memory/Memory.cpp:1368: u16 Memory::peek16(u32) [with long long int acc = 1; u16 = short unsigned int; u32 = unsigned int]: Assertion `IS_EVEN(addr)' failed.

Thread 8 "vAmiga" received signal SIGABRT, Aborted.
[Switching to Thread 0x7fffe34f9700 (LWP 15327)]
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff792a859 in __GI_abort () at abort.c:79
#2  0x00007ffff792a729 in __assert_fail_base (fmt=0x7ffff7ac0588 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n",
    assertion=0x55555586213b "IS_EVEN(addr)",
    file=0x5555558610a8 "/mnt/c/Prog/amiga/Misc/vAmiga/Emulator/Memory/Memory.cpp", line=1368,
    function=<optimized out>) at assert.c:92
#3  0x00007ffff793bf36 in __GI___assert_fail (assertion=0x55555586213b "IS_EVEN(addr)",
    file=0x5555558610a8 "/mnt/c/Prog/amiga/Misc/vAmiga/Emulator/Memory/Memory.cpp", line=1368,
    function=0x5555558624f0 "u16 Memory::peek16(u32) [with long long int acc = 1; u16 = short unsigned int; u32 = unsigned int]") at assert.c:101
#4  0x00005555557bec26 in Memory::peek16<1ll> (this=0x7fffffa35670, addr=490081)
    at /mnt/c/Prog/amiga/Misc/vAmiga/Emulator/Memory/Memory.cpp:1368
#5  0x000055555558ee01 in Agnus::doBitplaneDmaRead<0> (this=0x7fffffa369c0)
    at /mnt/c/Prog/amiga/Misc/vAmiga/Emulator/Agnus/AgnusDma.cpp:489
#6  0x0000555555592430 in Agnus::serviceBPLEventLores<0l> (this=0x7fffffa369c0)
    at /mnt/c/Prog/amiga/Misc/vAmiga/Emulator/Agnus/AgnusEvents.cpp:506
#7  0x0000555555591130 in Agnus::serviceBPLEvent (this=0x7fffffa369c0, id=4 '\004')
    at /mnt/c/Prog/amiga/Misc/vAmiga/Emulator/Agnus/AgnusEvents.cpp:273
#8  0x000055555559a3f6 in Scheduler::executeUntil (this=0x7fffffa36ca8, cycle=3275759352)
    at /mnt/c/Prog/amiga/Misc/vAmiga/Emulator/Agnus/Scheduler.cpp:500
```

Address comes from here:

```
(gdb) p/x bplpt
$1 = {0x77a61, 0x4ed30, 0x4ed58, 0x4ed80, 0x6c70c, 0x6c734}
```

The part has a copperlist, that does stuff like this:
```
00079514: 0102 0007     ;  BPLCON1 := $0007
00079518: 00e2 5e73     ;  BPL1PTL := $5e73
0007951c: 7001 fffe     ;  Wait for vpos >= $70 and hpos >= $00
                        ;  VP 70, VE 7f; HP 00, HE fe; BFD 1
00079520: 0102 0007     ;  BPLCON1 := $0007
00079524: 00e2 5ea5     ;  BPL1PTL := $5ea5
```

This can be fixed by:
```
--- a/Emulator/Agnus/AgnusRegisters.cpp
+++ b/Emulator/Agnus/AgnusRegisters.cpp
@@ -749,7 +749,7 @@ Agnus::setBPLxPTL(u16 value)
     if (dropWrite(BUS_BPL1 + x - 1)) return;

     // Perform the write
-    bplpt[x - 1] = REPLACE_LO_WORD(bplpt[x - 1], value);
+    bplpt[x - 1] = REPLACE_LO_WORD(bplpt[x - 1], value & 0xFFFE);
 }
```

Looks like you just forgot to carry the masking over, however you may want to review the other places where you replace the loword of pointers, since I think `setDSKPTL` and `setSPRxPTL` may have the same issue.

**Comment by dirkwhoffmann** [comment]
Yes, your are right. I accidentally dropped some of the AND masks when I cleaned up the code that checks for dropped pointer writes. The masks are back now.
